import OpenAI from 'openai';
import { Hono } from 'hono';
import {cors} from 'hono/cors';

type Bindings={
	OPEN_AI_KEY:string;
	AI:Ai;
}

const app = new Hono <{Bindings:Bindings}>();


app.use(
	'/*',
	cors({
	  origin: '*',
	  allowHeaders: ['X-Custom-Header', 'Upgrade-Insecure-Requests',"Content-Type"],
	  allowMethods: ['POST', 'GET', 'OPTIONS','PUT'],
	  exposeHeaders: ['Content-Length', 'X-Kuma-Revision'],
	  maxAge: 600,
	  credentials: true,
	})
  )


app.post('/chattoai',async(c)=>{
	const body=await c.req.json();
	const {documentdata,question}=body;
	const messages = [
		{ role: "system", content: "You are a friendly assistant,who contains knowledge in this document "+documentdata+" and removes all the extra components generated by Yjs.Doc and generate remaining meaning full sentences." },
		{
		  role: "user",
		  content: question,
		},
	  ];
	  const response = await c.env.AI.run("@cf/meta/llama-2-7b-chat-fp16", { messages });

	  return  Response.json(response);
})

app.post('/translateDocument',async(c)=>{
	const body=await c.req.json();
	const {documentdata,targetlang}=body;
	//summaries document

	const summaryresponse=await c.env.AI.run("@cf/facebook/bart-large-cnn",{
		input_text:documentdata,
		max_length:1000,
	});
	//translate
	const response= await c.env.AI.run("@cf/meta/m2m100-1.2b",{
		text:summaryresponse.summary,
		source_lang:"english",
		target_lang:targetlang,
	});
	console.log("response",response);
	return new Response(JSON.stringify(response));
})

export default app;
